function AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X) 


% Figura 
figure('Name','Amplificator INVERSOR',...
    'Units','normalized',...
    'Position',[0.05 0.05 0.8 0.85],...
    'NumberTitle','off','color','[0.6, 0.8, 1]');

% Meniu
fig=uimenu('Label','Proiect');                                                            
uimenu(fig,'Label','Documentatie1','Callback','Documentatie1');     
uimenu(fig,'Label','Prezentare1','Callback','Prezentare1');                          
uimenu(fig,'Label','Close','Callback','close',...                                                        
'Separator','on','Accelerator','Q');

% Titlu
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.9 0.6 0.05],...
 'backgroundcolor','[0.6, 0.8, 1]',... 
 'foregroundcolor','black',...
  'fontweight', 'bold',...
  'fontsize', 20,...
 'String','Amplificator operational Inversor');


  x=imread('schema.jpg');  
        image(x);
        axis off;            
        set(gca,'Position',[0.05 0.5 0.42 0.37]); 

   % Chenare
      RadioGroup1=uibuttongroup('Visible','on',...
        'BackgroundColor', '[1, 1, 0.8]',...
        'ForegroundColor','black',...
        'Title','Parametrii Circuitului',...
        'FontSize',13,...
        'Position',[0.05, 0.09, 0.2, 0.3],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');

      RadioGroup2=uibuttongroup('Visible','on',...
        'BackgroundColor', '[1, 1, 0.8]',...
        'ForegroundColor','BLACK',...
        'Title','Semnal de Intrare',...
        'FontSize',13,...
        'Position',[0.27 0.04 0.2 0.4],...
        'TitlePosition','centertop',...
        'Tag','radiobutton');

      RadioGroup3=uibuttongroup('Visible','on',...
        'BackgroundColor','[0.6, 0.8, 1]',...
        'ForegroundColor','black',...
        'Title','Tipul semnalului',...
        'FontSize',13,...
        'Position',[0.1 0.04 0.8 0.35],...
        'TitlePosition','centertop',...
        'Tag','radiobutton',...
         'Parent',RadioGroup2);

  %Parametrii circuitului
  % Alimentare negativa
      uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.83 0.4 0.12],...
        'backgroundcolor',[0.6, 0.8, 1],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','-Val[V]',...
        'Parent',RadioGroup1);

     uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.83 0.3 0.12],...
        'FontSize',12,...
        'String', Vminus,...
        'FontWeight','Bold',...
        'Parent',RadioGroup1,...
        'Callback',['Vminus=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X) ']);

   % Alimentare pozitiva

  uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.11 0.70 0.4 0.12],...
 'backgroundcolor',[0.6, 0.8, 1],...
 'foregroundcolor','black',...
 'FontSize',15,...
 'String','+Val[V]',...
 'Parent', RadioGroup1); 


   uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.70 0.3 0.12],...
        'FontSize',12,...
        'String', Vplus,...
        'FontWeight','Bold',...
        'Parent',RadioGroup1,...
        'Callback',['Vplus=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X) ']);

 % R1 
      uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.57 0.4 0.12],...
        'backgroundcolor',[0.6, 0.8, 1],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','R1[KOhm]',...
        'Parent',RadioGroup1);
    
      uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.57 0.3 0.12],...
        'FontSize',12,...
        'String', R1,...
        'FontWeight','Bold',...
        'Parent',RadioGroup1,...
        'Callback',['R1=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X) ']);

   % R2 
      uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.44 0.4 0.12],...
         'backgroundcolor',[0.6, 0.8, 1],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','R2[KOhm]',...
        'Parent',RadioGroup1);
    
      uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.44 0.3 0.12],...
        'FontSize',12,...
        'String', R2,...
        'FontWeight','Bold',...
        'Parent',RadioGroup1,...
        'Callback',['R2=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X)']);

   % P 
      uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.11 0.31 0.4 0.12],...
         'backgroundcolor',[0.6, 0.8, 1],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','P[KOhm]',...
        'Parent',RadioGroup1);
    
      uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.55 0.31 0.3 0.12],...
        'FontSize',12,...
        'String', P,...
        'FontWeight','Bold',...
        'Parent',RadioGroup1,...
        'Callback',['P=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X)']);

      %Semnal de intrare
% Tensiunea de Intrare

 uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.15 0.85 0.3 0.12],...
         'backgroundcolor',[0.6, 0.8, 1],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','A[V]',...
        'Parent',RadioGroup2);
   uicontrol('Style','edit',...
        'Units','normalized',...
        'String',A,...
        'Position',[0.55 0.85 0.3 0.12],...
        'FontSize',12,...
        'Parent',RadioGroup2,...
        'Callback',['A=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X)']);

  
   % Frecventa
      uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.15 0.7 0.3 0.12],...
         'backgroundcolor',[0.6, 0.8, 1],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','f[KHz]',...
        'Parent',RadioGroup2);
      uicontrol('Style','edit',...
        'Units','normalized',...
        'String',f,...
        'Position',[0.55 0.7 0.3 0.12],...
        'FontSize',12,... 
        'Parent',RadioGroup2,...    
        'Callback',['f=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X)']);

   % Offset
      uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.15 0.55 0.3 0.12],...
        'backgroundcolor',[0.6, 0.8, 1],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','Offset',...
        'Parent',RadioGroup2);
        uicontrol('Style','edit',...
        'Units','normalized',...
        'String',X,...
        'Position',[0.55 0.55 0.3 0.12],...
        'FontSize',12,... 
        'Parent',RadioGroup2,...
        'Callback',['X=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X) ']);

    % Perioada
      uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.15 0.4 0.3 0.12],...
        'backgroundcolor',[0.6, 0.8, 1],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','N',...
        'Parent',RadioGroup2);
    
      uicontrol('Style','edit',...
        'Units','normalized',...
        'String',N,...
        'Position',[0.55 0.4 0.3 0.12],...
        'FontSize',12,... 
        'Parent',RadioGroup2,...
        'Callback',['N=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X) ']);

% Tipuri de semnal
       Bp_u=uicontrol('Style','PopupMenu',...
                      'Units','normalized',...
                      'Position',[0.15 0.4 0.8 0.5],...
                      'value',semnal,...
                      'FontSize',12,...
                      'FontWeight','bold',...
                      'foregroundColor','black',...
                      'backgroundColor',[1, 1, 0.8],...
                      'String','Sinusoidal|Triunghiular|Dreptunghiular',...
                      'Parent',RadioGroup3,...
                      'Callback','semnal=get(gco,''value'');close;AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X) ');

     %Buton
 uicontrol('Style','pushbutton',...
             'Units','normalized',...
             'Position',[0.89 0.015 0.1 0.06],...
             'FontWeight','bold',...
             'FontSize',13,...
             'String','Inapoi',...
             'Callback','close;interfata');  
T=1/f;
t=0:T/100:N*T; 

%Amplificarea
Av=-(R2+k*P)/R1;

Vimin=Vplus/Av;
Vimax=Vminus/Av;

%afisare amplificare
  Bp_t=uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.47 0.08 0.30 0.04],...
          'backgroundcolor',[1, 1, 0.8],...
          'foregroundcolor','black',...
          'fontweight', 'bold',...
          'fontsize', 15,...
          'String','Amplificarea');

     uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.47 0.04 0.37 0.04],...
          'backgroundcolor',[1, 1, 0.8],...
          'foregroundcolor', 'black' ,...
          'fontweight', 'bold',...
          'fontsize', 15,...
          'String',Av);

   %Repetor de tensiune
      if(Av==-1)
    uicontrol('Style','text',... 
'Units','normalized',...
'Position',[0.2 0.45 0.2 .03],...
'FontWeight','bold',...
'Fontsize',12,...
'backgroundcolor',[0.70196   0.49804      0.4],...
'foregroundcolor','black',...
'string','Repetor de tensiune inversor');
      end

 

  %Tipuri semnal
if semnal==1   %semnal sinusoidal
    Vi=X+A*sin(2.*3.14.*f*t);
    Vo=Av*Vi;
    
end
if semnal==2     %semnal triunghiular
    Vi=X+(2*A/pi)*asin(sin(2.*3.14.*f*t));
    Vo=Av*Vi;
    
end
if semnal==3      %semnal dreptunghiular
 
   Vi=X+A*sign(sin(2*3.14.*t));
   Vo=Av*Vi;
end      

%Limitarea tensiunii de iesire
    
k=max(size(t));
for i=1:k
    if (Vo(i)>Vplus) 
        Vo(i)=Vplus;
    end
    if (Vo(i)<Vminus)
        Vo(i)=Vminus; 
    end
end

 %Afisare semnal     
subplot('position',[0.55 0.6 0.4 0.2]);
 plot(t,Vo,'-black','LineWidth',2);   
            hold on;
            txt= '\leftarrow Vo';   
            text(0.6,3,txt,'color','b');
  
            
  plot(t,Vi,'-.r','LineWidth',2);     
            txt= 'Vi \rightarrow ';    
            text(0.45,-3.5,txt,'color','k');
            grid on; 
   ylim([Vminus-A-2 Vplus+A+2]);         

title('Tensiunea de intrare/ieșire [Vi/Vo]','FontSize',15,'color','black');
        xlabel('timp [ms]','color','black');
        ylabel('Amplitudine [V]','color','black');   
        legend('Vo','Vi');  

  Ph=max(Vi); %Calcul vi max
         Pl=min(Vi); %Calcul vi min     

% Ri - Rezistenta de intrare
            
            Ri=R1;
      uicontrol('Style','text',... 
                'Units','normalized',...
                'Position',[0.11 0.18 0.4 0.12],...
                'backgroundcolor',[0.6, 0.8, 1],...
                'foregroundcolor','black',...
                'FontSize',15,...
                'String','Ri[KOhm]',...
                'Parent',RadioGroup1);
 uicontrol('Style','edit',...
                'Units','normalized',...
                'Position',[0.55 0.18 0.3 0.12],...
                'FontSize',12,...
                'String', Ri,...
                'FontWeight','Bold',...
                'Parent',RadioGroup1,...
               'Callback',['Ri=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X) ']);

% Ro - Rezistenta de iesire 
    for i=1
        Isc=inf;
        Ro=abs(Vo(i))./Isc;
    end

    uicontrol('Style','text',... 
                'Units','normalized',...
                'Position',[0.11 0.05 0.4 0.12],...
                'backgroundcolor',[0.6, 0.8, 1],...
                'foregroundcolor','black',...
                'FontSize',15,...
                'String','Ro[KOhm]',...
                'Parent',RadioGroup1);
     uicontrol('Style','edit',...
                'Units','normalized',...
                'Position',[0.55 0.05 0.3 0.12],...
                'FontSize',12,...
                'String', Ro,...
                'FontWeight','Bold',...
                'Parent',RadioGroup1,...
                'Callback',['Ri=','str2num(get(gco,''String'')),close,AOinv(Vplus,Vminus,A,f,N,R1,R2,P,semnal,k,X)']);

     %CSTV
 subplot('position',[0.55 0.23 0.4 0.2]);

        plot(Vi,Vo,'-r');
hold on;
grid on;
axis([Pl-2 Ph+2 Vminus-2 Vplus+2])   

 title('Caracteristica statică de transfer în tensiune [CSTV]','FontSize',15,'color','black');
    xlabel('[ Vi ]','color','black');
    ylabel('[ Vo ]','color','black');   

    if R1<=0 || R2<=0 || P<0
       errordlg('Rezistentele nu pot fi negative!');
    end

    if N<1
          errordlg('Perioada minima este 1!');
    end
end


