%Figura 
figure('Name','Amplificator INVERSOR',...
    'Units','normalized',...
    'Position',[0.05 0.05 0.8 0.85],...
    'NumberTitle','off','color','[1, 1, 0.8]');

% Meniu
fig=uimenu('Label','Proiect');
uimenu(fig,'Label','Documentatie1','Callback','Documentatie1');% Teorie
uimenu(fig,'Label','Prezentare1','Callback','Prezentare1');% Prezentare
uimenu(fig,'Label','Close','Callback','close',...
'Separator','on','Accelerator','Q');
   
% Titlu
Bt=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.9 0.6 0.05],...
 'backgroundcolor',[1, 1, 0.8],... 
 'foregroundcolor','black',...
  'fontweight', 'bold',...
  'fontsize', 25,...
 'String','Amplificator operațional Inversor');

% Butoane
buttonWidth = 0.2;
buttonHeight = 0.1;

uicontrol('Style','pushbutton',...
          'Units','normalized',...
          'Position',[0.2 0.60 0.2 0.1],...
          'backgroundcolor',	'[0.6, 0.8, 1]',...
          'FontSize',12,...
          'String','Amplificator operațional inversor',...
          'Callback','inversor_start');

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.2 0.45 0.2 0.1],...
    'FontSize',12,...
    'String','Documentatie1',...
    'backgroundcolor',	'[0.6, 0.8, 1]',...
    'Callback','Documentatie1;');

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.2 0.30 0.2 0.1],...
    'backgroundcolor',	'[0.6, 0.8, 1]',...
    'FontSize',12,...
    'String','Prezentare1',...
    'Callback','Prezentare1;');

% Adaugare imagine
img = imread('amplificator.jpg'); 
axesPosition = [0.5 0.3 0.4 0.5];
ax = axes('Position', axesPosition);
imshow(img, 'Parent', ax);

uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.7 0.1 0.2 0.05],...
          'backgroundcolor', [0.6, 0.8, 1],...
          'foregroundcolor',[0 0 0 0],...
          'fontsize',15,...
          'String','Nume: Gherasim Evelina');

uicontrol('Style','text',...
          'Units','normalized',...
          'Position', [0.7 0.05 0.2 0.05],...
          'backgroundcolor', [0.6, 0.8, 1],...
          'foregroundcolor',[0 0 0 0],...
          'fontsize',15,...
          'String','Grupa: 2121');
